#!/bin/sh

OUTPUT=$(dotnet test)
RESULT=0

while read -r LINE; do
	echo $LINE
    if [[ $LINE == *"Aprovado"* ]] || [[ $LINE == *"Passed"* ]]
	then
		RESULT=1
		break
	elif [[ $LINE == *"MSB1003"* ]]
	then
		RESULT=2
		break
	elif [[ $LINE == *"Com falha"* || $LINE == *"Failed"* ]]
	then
		RESULT=0
		break
    fi
done <<< "$OUTPUT"

if [[ $RESULT == 1 ]]
then
	echo "Todos os testes passaram, efetuando commit..."
	exit 0
elif [[ $RESULT == 2 ]]
then
	echo "Este projeto não possui testes, efetuando commit..."
	exit 0
else
	echo "Não foi possível continuar com o commit pois um ou mais testes não passaram. Por favor, verifique o(s) projeto(s) de teste e tente novamente."
	exit 1
fi
